service: sales-api
frameworkVersion: '3'
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: 'GET /product/donut'
      - httpApi: 'POST /checkout'
    # environment:
    #   HOSTNAME: ${env:HOSTNAME}
    #   USERNAME: ${env:USERNAME}
    #   PASSWORD: ${env:PASSWORD}
    #   DATABASE: ${env:DATABASE}
