service: sales-api
frameworkVersion: "3"
plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2

resources:
  Resources:
    StockEmpty:
      Type: "AWS::SNS::Topic"
      Properties:
        TopicName: stock-empty.fifo
        FifoTopic: true
  Outputs:
    StockEmptyArn:
      Value: !Ref StockEmpty
      Export:
        Name: StockEmptyArn

functions:
  sales-api:
    handler: handler.handler
    events:
      - httpApi: "GET /product/donut"
      - httpApi: "POST /checkout"
    destinations:
      onSuccess:
        type: sns
        arn:
          Ref: StockEmpty
